"""msg=plc health + incident tables

Revision ID: 13eeb0cb4f16
Revises: a7c2e9f04b18
Create Date: 2026-06-21 11:54:59.670332

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13eeb0cb4f16"
down_revision: str | Sequence[str] | None = "a7c2e9f04b18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plc_health",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plc_ip", sa.String(length=45), nullable=False),
        sa.Column("plc_name", sa.String(length=255), nullable=False),
        sa.Column("rack", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("connected", sa.Boolean(), nullable=False),
        sa.Column("last_success_at", sa.DateTime(), nullable=True),
        sa.Column("consecutive_fail", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.String(length=512), nullable=True),
        sa.Column("good_last_cycle", sa.Integer(), nullable=False),
        sa.Column("bad_last_cycle", sa.Integer(), nullable=False),
        sa.Column("reconnects_last_min", sa.Integer(), nullable=False),
        sa.Column("open_incident_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plc_ip", "rack", "slot", name="uq_plc_health_key"),
    )
    op.create_table(
        "plc_incidents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plc_ip", sa.String(length=45), nullable=False),
        sa.Column("plc_name", sa.String(length=255), nullable=False),
        sa.Column("rack", sa.Integer(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=255), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("notified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plc_incidents_opened_at"), "plc_incidents", ["opened_at"], unique=False
    )
    op.create_index(op.f("ix_plc_incidents_plc_ip"), "plc_incidents", ["plc_ip"], unique=False)
    op.create_index(
        op.f("ix_plc_incidents_resolved_at"), "plc_incidents", ["resolved_at"], unique=False
    )
    op.drop_index(op.f("ix_apscheduler_jobs_next_run_time"), table_name="apscheduler_jobs")
    op.drop_table("apscheduler_jobs")
    op.drop_index(
        op.f("ix_excel_template_columns_template_id"), table_name="excel_template_columns"
    )
    op.create_foreign_key(None, "tags", "tag_groups", ["group_id"], ["id"], ondelete="SET NULL")
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=150),
        existing_nullable=False,
    )
    op.drop_constraint(None, "tags", type_="foreignkey")
    op.create_index(
        op.f("ix_excel_template_columns_template_id"),
        "excel_template_columns",
        ["template_id"],
        unique=False,
    )
    op.create_table(
        "apscheduler_jobs",
        sa.Column("id", sa.VARCHAR(length=191), nullable=False),
        sa.Column("next_run_time", sa.FLOAT(), nullable=True),
        sa.Column("job_state", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apscheduler_jobs_next_run_time"),
        "apscheduler_jobs",
        ["next_run_time"],
        unique=False,
    )
    op.drop_index(op.f("ix_plc_incidents_resolved_at"), table_name="plc_incidents")
    op.drop_index(op.f("ix_plc_incidents_plc_ip"), table_name="plc_incidents")
    op.drop_index(op.f("ix_plc_incidents_opened_at"), table_name="plc_incidents")
    op.drop_table("plc_incidents")
    op.drop_table("plc_health")
    # ### end Alembic commands ###
