"""advanced_reporting

Revision ID: decf6c1fe08b
Revises: f7b7e5a26253
Create Date: 2026-06-15 14:40:50.878018

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "decf6c1fe08b"
down_revision: str | Sequence[str] | None = "f7b7e5a26253"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tag_ids", sa.Text(), nullable=False),
        sa.Column("time_range_type", sa.String(length=20), nullable=False),
        sa.Column("custom_start", sa.DateTime(), nullable=True),
        sa.Column("custom_end", sa.DateTime(), nullable=True),
        sa.Column("interval", sa.String(length=20), nullable=False),
        sa.Column("output_format", sa.String(length=10), nullable=False),
        sa.Column("include_std_dev", sa.Boolean(), nullable=False),
        sa.Column("include_percentiles", sa.Boolean(), nullable=False),
        sa.Column("percentile_levels", sa.Text(), nullable=False),
        sa.Column("include_trend_line", sa.Boolean(), nullable=False),
        sa.Column("anomaly_enabled", sa.Boolean(), nullable=False),
        sa.Column("anomaly_zscore_threshold", sa.Float(), nullable=False),
        sa.Column("show_summary_stats", sa.Boolean(), nullable=False),
        sa.Column("show_trend_charts", sa.Boolean(), nullable=False),
        sa.Column("show_anomaly_table", sa.Boolean(), nullable=False),
        sa.Column("show_raw_data", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "scheduled_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("schedule_type", sa.String(length=20), nullable=False),
        sa.Column("cron_hour", sa.Integer(), nullable=True),
        sa.Column("cron_minute", sa.Integer(), nullable=True),
        sa.Column("cron_day_of_week", sa.String(length=20), nullable=True),
        sa.Column("cron_day_of_month", sa.Integer(), nullable=True),
        sa.Column("interval_hours", sa.Integer(), nullable=True),
        sa.Column("apscheduler_job_id", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("last_run_status", sa.String(length=20), nullable=True),
        sa.Column("last_run_error", sa.Text(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["template_id"], ["report_templates.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("apscheduler_job_id"),
    )
    op.create_table(
        "report_archive",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("scheduled_report_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("tag_ids", sa.Text(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("interval", sa.String(length=20), nullable=False),
        sa.Column("output_format", sa.String(length=10), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("result_json", sa.LargeBinary(), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scheduled_report_id"], ["scheduled_reports.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["template_id"], ["report_templates.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_report_archive_status", "report_archive", ["status"], unique=False)
    op.create_index(
        "idx_report_archive_template_id", "report_archive", ["template_id"], unique=False
    )
    op.create_index(
        op.f("ix_report_archive_created_at"), "report_archive", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_archive_created_at"), table_name="report_archive")
    op.drop_index("idx_report_archive_template_id", table_name="report_archive")
    op.drop_index("idx_report_archive_status", table_name="report_archive")
    op.drop_table("report_archive")
    op.drop_table("scheduled_reports")
    op.drop_table("report_templates")
    # ### end Alembic commands ###
