"""alarm_thresholds_and_report_history

Revision ID: f7b7e5a26253
Revises: 97421fc62374
Create Date: 2026-06-15 01:51:12.792946

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7b7e5a26253"
down_revision: str | Sequence[str] | None = "97421fc62374"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("tag_ids", sa.Text(), nullable=False),
        sa.Column("start", sa.DateTime(), nullable=False),
        sa.Column("end", sa.DateTime(), nullable=False),
        sa.Column("interval", sa.String(length=20), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("file_path", sa.String(length=512), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("tags", sa.Column("min_alarm", sa.Float(), nullable=True))
    op.add_column("tags", sa.Column("max_alarm", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tags", "max_alarm")
    op.drop_column("tags", "min_alarm")
    op.drop_table("report_history")
    # ### end Alembic commands ###
